// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ForceDisconnect() {
  return window['go']['main']['App']['ForceDisconnect']();
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function SendAllPagesAsContinuousStream(arg1) {
  return window['go']['main']['App']['SendAllPagesAsContinuousStream'](arg1);
}

export function SendData(arg1) {
  return window['go']['main']['App']['SendData'](arg1);
}

export function SendDataSmart(arg1) {
  return window['go']['main']['App']['SendDataSmart'](arg1);
}

export function SendMultiplePages(arg1) {
  return window['go']['main']['App']['SendMultiplePages'](arg1);
}
